name: 'ECS Deploy'

on: 
  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: Select region
        default: us-east-1
        options: 
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
      env:
        type: choice
        default: staging
        description: Select environment to deploy
        options: 
          - production
          - staging
      containers:
        type: choice
        default: 2
        description: Select number of containers
        options: 
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS access'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS secret'
        required: true

permissions:
  contents: read

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
        TF_WORKSPACE: ${{ github.event.inputs.region }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: deployments/ecsdeploy

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    # This step is run when the tag is release-XXX
    - name: Sets env vars for staging
      if: github.event.inputs.env == 'staging'
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
    
     # This step is run when the tag is release-XXX
    - name: Sets env vars for production
      if: github.event.inputs.env == 'production'
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -target=module.ecs -var="num_containers=${{ github.event.inputs.containers }}" -var="region=${{ github.event.inputs.region }}" -var="env=${{ github.event.inputs.env }}" -input=true -out=.terraform/terraform.tfplan
  
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    needs: terraform-plan

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: deployments/ecsdeploy

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    # This step is run when the tag is release-XXX
    - name: Sets env vars for staging
      if: github.event.inputs.env == 'staging'
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
    
     # This step is run when the tag is release-XXX
    - name: Sets env vars for production
      if: github.event.inputs.env == 'production'
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
    
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt 

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -target=module.ecs -var="num_containers=${{ github.event.inputs.containers }}" -var="region=${{ github.event.inputs.region }}" -var="env=${{ github.event.inputs.env }}" -input=true -out=.terraform/terraform.tfplan
    
    # Generates an execution plan for Terraform
    - name: Terraform Apply
      run: terraform apply -target=module.ecs -input=true .terraform/terraform.tfplan